### ISSUE TITLE
wrong path to example script

### ISSUE THREAD

**Issue by laurentGithpe** [k8s-school/k8s-school#1]
```shell
# Retrieve examples
./homefs/clone-book-examples.sh 
# Play with kubectl and yaml files :-)
```

**Comment by kammous** [comment]
Hi Laurent and thanks for your comment.
examples are meant to be executed from inside kubectl container. Its $home is mounted to the folder you are referring to. I added a comment to make it clear.
Thanks again.

**Comment by laurentGithpe** [comment]
Hi Karim
your comment is crystal clear.
